type   Project  = {
    PROJECT_SHORT_NAME : string
    PROJECT_NAME : string
    PROJECT_IMG : string 
    js : string 
    tailwind : string 
    mui : string 
    react : string 
    redux : string 
    icons : string 
    pusher : string 
    nodejs : string 
    Express : string 
    mongodb : string
    Firebase  : string 
    mysql   : string 
    postger : string 
    prisma  : string
    Nextjs : string 
    Ts : string 
    LIVE_MODE : string 
    PROJECT_TEXT : string 
    PROJECT_VIDEO : string 
    Frontend_Repo_Link  : string
    Backend_Repo_Link  : string
    langauge_Frontend : string[] 
    langauge_Backend : string[] 
    USER_LANGUAGE_IMG : string[] 
}